services:
  - type: web
    name: custom-ecommerce-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 4000
      - key: TARGET_PROFIT_MARGIN
        value: 0.15
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_OWNER_CHAT_ID
        sync: false
      - key: PRINTIFY_API_TOKEN
        sync: false
      - key: PRINTIFY_SHOP_ID
        sync: false
